export const GET_BALANCE = 'GET_BALANCE';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const ADD_TO_BALANCE = 'ADD_TO_BALANCE';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const SUB_BALANCE = 'SUB_BALANCE';

export const GET_DICA = 'GET_DICA';
export const GET_DICA_ATUAL = 'GET_DICA_ATUAL';
export const SET_DICA = 'SET_DICA';
